Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/Cart.cshtml.cs
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Cart;
using UiS.Dat240.Lab3.Core.Domain.Cart.Pipelines;
using UiS.Dat240.Lab3.Helpers;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.InteropServices;
using System;

namespace UiS.Dat240.Lab3.Pages;

public class CartModel : PageModel
{
	private readonly IMediator _mediator;

	public CartModel(IMediator mediator) => _mediator = mediator ?? throw new System.ArgumentNullException(nameof(mediator));

	public ShoppingCart? Cart { get; private set; }

	public async Task OnGetAsync()
	{
		var cartId = HttpContext.Session.GetGuid("CartId");
		if (cartId is null) return;

		Cart = await _mediator.Send(new Get.Request(cartId.Value));
	}

	public async Task<IActionResult> OnPostAsync(string customerName, string building, string roomNumber, string locationNotes){
		var cartId = HttpContext.Session.GetGuid("CartId");
		if (cartId is null){
			return Page();
		}
		await _mediator.Send(new CartCheckout.Request(cartId.Value, building, roomNumber, locationNotes, customerName));
		return RedirectToPage("OrderOverview");
	}
}

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace UiS.Dat240.Lab3.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
	public string RequestId { get; set; } = "";

	public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

	private readonly ILogger<ErrorModel> _logger;

	public ErrorModel(ILogger<ErrorModel> logger)
	{
		_logger = logger;
	}

	public void OnGet()
	{
		RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
	}
}

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Products;
using UiS.Dat240.Lab3.Helpers;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UiS.Dat240.Lab3.Pages;

public class IndexModel : PageModel
{
	private readonly IMediator _mediator;
	public IndexModel(IMediator mediator) => _mediator = mediator;

	public List<FoodItem> FoodItems { get; set; } = new();

	public async Task OnGetAsync()
		=> FoodItems = await _mediator.Send(new Core.Domain.Products.Pipelines.Get.Request());

	public async Task<IActionResult> OnPostAddToCartAsync(int id, string name, decimal price)
	{
		var cartId = HttpContext.Session.GetGuid("CartId");
		if (cartId == null)
		{
			cartId = Guid.NewGuid();
			HttpContext.Session.SetString("CartId", cartId.ToString());
		}

		await _mediator.Send(new Core.Domain.Cart.Pipelines.AddItem.Request(id, name, price, cartId.Value));

		return RedirectToPage();
	}
}

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/OrderDetails.cshtml.cs
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Cart;
using UiS.Dat240.Lab3.Core.Domain.Cart.Pipelines;
using UiS.Dat240.Lab3.Helpers;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using UiS.Dat240.Lab3.Core.Domain.Ordering.Dto;
using System;
using UiS.Dat240.Lab3.Infrastructure.Data;
using System.Collections.Generic;
using UiS.Dat240.Lab3.Core.Domain.Ordering;
using Microsoft.EntityFrameworkCore;
using UiS.Dat240.Lab3.Core.Domain.Fulfillment.Pipelines;
using UiS.Dat240.Lab3.Core.Domain.Fulfillment;
using UiS.Dat240.Lab3.Core.Domain.Invoicing;


namespace UiS.Dat240.Lab3.Pages;

public class OrderDetailsModel : PageModel{
    private readonly ShopContext _db;
    private readonly IMediator _mediator;
    public OrderDetailsModel(ShopContext db, IMediator mediator){
        _db = db;
        _mediator = mediator;
    }
    public Order Order {get; set;}
    public Offer Offer {get; set;}
    public Reimbursement Reimbursement {get; set;}
    public Shipper Shipper {get; set;}
    public Invoice Invoice{get; set;}
    public async Task OngetAsync(Guid orderId){
        Order = await _db.Orders.Include(o => o.Customer).Include(o=> o.Location).Include(o=> o.OrderLines).SingleOrDefaultAsync(o=>o.Id== orderId);
        Offer = await _db.Offers.Include(o => o.Reimbursement).Include(o => o.Shipper).SingleOrDefaultAsync(o=>o.OrderId == orderId);
        Invoice = await _db.Invoices.Include(o => o.Address).SingleOrDefaultAsync(o => o.OrderId == orderId);
    }
    public async Task<IActionResult> OnPostAsync(Guid orderId, string shipperName){
        await _mediator.Send(new SetShipper.Request(orderId, shipperName));
        return RedirectToPage("OrderOverview");
    }
}

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/OrderOverview.cshtml.cs
using System.Threading.Tasks;
using UiS.Dat240.Lab3.Core.Domain.Cart;
using UiS.Dat240.Lab3.Core.Domain.Cart.Pipelines;
using UiS.Dat240.Lab3.Helpers;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using UiS.Dat240.Lab3.Core.Domain.Ordering.Dto;
using System;
using UiS.Dat240.Lab3.Infrastructure.Data;
using System.Collections.Generic;
using UiS.Dat240.Lab3.Core.Domain.Ordering;
using Microsoft.EntityFrameworkCore;


namespace UiS.Dat240.Lab3.Pages;

public class OrderOverviewModel : PageModel{
    private readonly ShopContext _db;
    public OrderOverviewModel(ShopContext db){
        _db = db;
    }
    public List<Order> Orders {get; set;}

    public async Task OnGetAsync(){
        Orders = await _db.Orders.Include(o => o.Customer).Include(o => o.Location).ToListAsync();
    }
}

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/Cart.cshtml
@page
@model Lab3.Pages.CartModel
@{
	ViewData["Title"] = "Shopping cart";
}

<div class="text-center mt-4">

	<h1 class="display-4 mt-5">Your cart</h1>
	<div class="text-left">
		@if (Model.Cart is null)
		{
			<p>There is nothing in your cart</p>
		}
		else
		{
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Dish</th>
						<th scope="col">Count</th>
						<th scope="col">Price</th>
						<th scope="col">Sum</th>
					</tr>
				</thead>
				<tbody>

					@foreach (var item in Model.Cart.Items)
					{
						<tr>
							<th scope="row">@item.Name</th>
							<td>@item.Count</td>
							<td>@item.Price</td>
							<td>@item.Sum</td>
						</tr>
					}
				</tbody>
			</table>
			<button id="confirmOrderBtn" onclick="showCustomerForm()">Confirm Order</button>

			<div id="customerForm" style="display: none; margin-top: 20px;">
				<h3>Enter your details to complete the order</h3>
				<form method="post">
					<div class="form-group">
						<label for="customerName">Name:</label>
						<input type="text" id="customerName" name="customerName" required/>
					</div>
					
					<div class="form-group">
						<label for="Building">Building:</label>
						<input type="text" id="Building" name="Building" required/>
					</div>

					<div class="form-group">
						<label for="RoomNumber">RoomNumber:</label>
						<input type="text" id="RoomNumber" name="RoomNumber" required />
					</div>
					
					<div class="form-group">
						<label for="LocationNotes">Notes:</label>
						<input type="text" id="LocationNotes" name="LocationNotes"/>
					</div>
					

					<button type="submit">Confirm Order</button>
				
				</form>
			</div>
		}
	</div>
</div>
<script>
	function showCustomerForm(){
		document.getElementById("customerForm").style.display = "block";
	}
</script>

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<form method="post">
<div class="text-center">
    <h1 class="display-4 mt-5">Menu</h1>

    @for (int index = 1; index <= 3; index++)
{
    <div class="menu">
            <img src="~/img/Menu0@(index).png" />

            <ul>
                @foreach (var item in Model.FoodItems.Skip((index - 1) * 8).Take(8))
            {

                <li>
                        <div class="header">
                            <h2>@item.Name</h2>
                            <p class="price">Kr @string.Format("{0:#0.00}",item.Price)</p>
                        </div>
                        <div class="body">
                            <div>

                                <p class="text">@item.Description</p>
                                <p class="cooking-time">@item.CookTime min</p>
                            </div>
                            <button type="submit" asp-page-handler="AddToCart"
                                asp-route-id="@item.Id"
                                asp-route-name="@item.Name"
                                asp-route-price="@item.Price.ToString("0..00")"
                                  ><img src="~/img/addToCart.svg" height="20" width="20">
                            </button>
                            
                        </div>
                    </li>
            }
            </ul>
        </div>
}


</div>
</form>

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/OrderDetails.cshtml
@page "{orderId:Guid}"
@using UiS.Dat240.Lab3.Core.Domain.Ordering
@using UiS.Dat240.Lab3.Core.Domain.Fulfillment
@model Lab3.Pages.OrderDetailsModel
@{
    ViewData["Title"] = "Order Details";
}

<h2>Order Details</h2>
<div>
    <p>Id: @Model.Order.Id</p>
    <p>Status: @Model.Order.Status</p>
    <p>Order Date: @Model.Order.OrderDate</p>
</div>
<div>
    <h3>Customer Information</h3>
    <p>Name: @Model.Order.Customer.Name</p>
    <p>Building: @Model.Order.Location.Building</p>
    <p>Room Numer: @Model.Order.Location.RoomNumber</p>
    <p>Notes: @Model.Order.Location.Notes</p>
</div>

<div>
    <h3>Order Items</h3>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Order.OrderLines)
            {
                <tr>
                    <td>@item.ItemName</td>
                    <td>@item.Amount</td>
                    <td>@item.Price</td>
                    <td>@(item.Price * item.Amount)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

  <h3>Invoice Details</h3>
    <p>Id: @Model.Invoice.Id</p>
    <p>Amount: @Model.Invoice.Amount</p>
    <p>Status: @Model.Invoice.Status</p>
<h3>Shipper info</h3>
@if (Model.Order.Status == Status.Placed){
    <div>
        <p>No shipper</p>
        <form method="post">
            <label>Assign Shipper</label>
            <input type="text" name="shipperName"/>
            <button type="submit">Assign</button>
        </form>
    </div>
}


@if (Model.Order.Status == Status.Shipped){
    <div>
        <p>Id: @Model.Offer.Reimbursement.Shipper.Id</p>
        <p>Shipper Name: @Model.Offer.Shipper.Name</p>

    </div>


}

Uis/5-Semester/Dat240/Assignments/Lab3/UiS.Dat240.Lab3/Pages/OrderOverview.cshtml
@page
@model Lab3.Pages.OrderOverviewModel
@{
    ViewData["Title"] = "Order Overview";
}

<div class="text-center mt-4">
    <h1 class="display-4 mt-5">Order Overview</h1>
    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Customer</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model.Orders){
                <tr>
                    <td>@order.Id</td>
                    <td>@order.Customer.Name</td>
                    <td>@order.Status</td>
                    <td><a asp-page="OrderDetails" asp-route-orderId="@order.Id">View</a></td>
                </tr>
            }
        </tbody>
    </table>


</div>